"""initial schema - 44 tables

Revision ID: 51468ce1356a
Revises:
Create Date: 2026-03-24 22:57:52.767259

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51468ce1356a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("sort_name", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "dj_playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("source_app", sa.String(length=200), nullable=True),
        sa.Column(
            "source_of_truth", sa.String(length=100), server_default="local", nullable=False
        ),
        sa.Column("platform_ids", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["dj_playlists.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["genres.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "keys",
        sa.Column("key_code", sa.Integer(), nullable=False),
        sa.Column("pitch_class", sa.Integer(), nullable=False),
        sa.Column("mode", sa.Integer(), nullable=False, comment="0=minor, 1=major"),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("camelot", sa.String(length=3), nullable=False, comment="e.g. 8A, 11B"),
        sa.CheckConstraint("key_code >= 0 AND key_code <= 23", name="ck_key_code_range"),
        sa.CheckConstraint("mode IN (0, 1)", name="ck_mode_binary"),
        sa.CheckConstraint("pitch_class >= 0 AND pitch_class <= 11", name="ck_pitch_class_range"),
        sa.PrimaryKeyConstraint("key_code"),
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "spotify_album_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spotify_album_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("album_type", sa.String(length=50), nullable=True),
        sa.Column("total_tracks", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.String(length=50), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spotify_album_id"),
    )
    op.create_table(
        "spotify_artist_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spotify_artist_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("genres", sa.Text(), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spotify_artist_id"),
    )
    op.create_table(
        "spotify_playlist_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spotify_playlist_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("owner_id", sa.String(length=100), nullable=True),
        sa.Column("total_tracks", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spotify_playlist_id"),
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN (0, 1)", name="ck_track_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "app_exports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_app", sa.String(length=50), nullable=False),
        sa.Column("export_format", sa.String(length=50), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["playlist_id"], ["dj_playlists.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "beatport_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("beatport_track_id", sa.String(length=100), nullable=False),
        sa.Column("bpm", sa.Float(), nullable=True),
        sa.Column("key", sa.String(length=20), nullable=True),
        sa.Column("length", sa.String(length=20), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=True),
        sa.Column("genre", sa.String(length=200), nullable=True),
        sa.Column("subgenre", sa.String(length=200), nullable=True),
        sa.Column("release_date", sa.String(length=50), nullable=True),
        sa.Column("preview_url", sa.String(length=1000), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id"),
    )
    op.create_table(
        "dj_library_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("file_uri", sa.String(length=1000), nullable=True),
        sa.Column("file_hash", sa.String(length=128), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("source_app", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dj_playlist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("sort_index", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["playlist_id"], ["dj_playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playlist_id", "sort_index", name="uq_playlist_items_playlist_sort"),
    )
    op.create_table(
        "dj_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_duration_ms", sa.Integer(), nullable=True),
        sa.Column("target_bpm_min", sa.Float(), nullable=True),
        sa.Column("target_bpm_max", sa.Float(), nullable=True),
        sa.Column("target_energy_arc", sa.Text(), nullable=True),
        sa.Column("template_name", sa.String(length=200), nullable=True),
        sa.Column("source_playlist_id", sa.Integer(), nullable=True),
        sa.Column("ym_playlist_id", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_playlist_id"], ["dj_playlists.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("embedding_type", sa.String(length=50), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("vector_data", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id", "embedding_type", name="uq_embedding_track_type"),
    )
    op.create_table(
        "feature_extraction_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_name", sa.String(length=100), nullable=False),
        sa.Column("pipeline_version", sa.String(length=50), nullable=False),
        sa.Column("parameters", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')", name="ck_fer_status"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "key_edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_key_code", sa.Integer(), nullable=False),
        sa.Column("to_key_code", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("rule_name", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_key_code"],
            ["keys.key_code"],
        ),
        sa.ForeignKeyConstraint(
            ["to_key_code"],
            ["keys.key_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provider_track_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_track_id", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "track_id", "provider_id", name="uq_provider_track_ids_track_provider"
        ),
    )
    op.create_table(
        "raw_provider_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("raw_data", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("release_type", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["label_id"], ["labels.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "soundcloud_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("soundcloud_track_id", sa.String(length=100), nullable=False),
        sa.Column("playback_count", sa.Integer(), nullable=True),
        sa.Column("favoritings_count", sa.Integer(), nullable=True),
        sa.Column("reposts_count", sa.Integer(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=True),
        sa.Column("downloadable", sa.Boolean(), nullable=True),
        sa.Column("streamable", sa.Boolean(), nullable=True),
        sa.Column("permalink_url", sa.String(length=1000), nullable=True),
        sa.Column("artwork_url", sa.String(length=1000), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("genre", sa.String(length=200), nullable=True),
        sa.Column("tag_list", sa.String(length=2000), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("license", sa.String(length=100), nullable=True),
        sa.Column("created_at_sc", sa.String(length=50), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id"),
    )
    op.create_table(
        "spotify_audio_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("spotify_track_id", sa.String(length=100), nullable=False),
        sa.Column("danceability", sa.Float(), nullable=True),
        sa.Column("energy", sa.Float(), nullable=True),
        sa.Column("key", sa.Integer(), nullable=True),
        sa.Column("loudness", sa.Float(), nullable=True),
        sa.Column("mode", sa.Integer(), nullable=True),
        sa.Column("speechiness", sa.Float(), nullable=True),
        sa.Column("acousticness", sa.Float(), nullable=True),
        sa.Column("instrumentalness", sa.Float(), nullable=True),
        sa.Column("liveness", sa.Float(), nullable=True),
        sa.Column("valence", sa.Float(), nullable=True),
        sa.Column("tempo", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("time_signature", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id"),
    )
    op.create_table(
        "spotify_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("spotify_track_id", sa.String(length=100), nullable=False),
        sa.Column("album_id", sa.String(length=100), nullable=True),
        sa.Column("explicit", sa.Boolean(), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("preview_url", sa.String(length=1000), nullable=True),
        sa.Column("release_date", sa.String(length=50), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id"),
    )
    op.create_table(
        "timeseries_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("feature_set_name", sa.String(length=100), nullable=False),
        sa.Column("storage_uri", sa.String(length=1000), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("hop_length", sa.Integer(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("data_type", sa.String(length=20), nullable=False),
        sa.Column(
            "shape", sa.String(length=100), nullable=False, comment="JSON-like shape descriptor"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track_artists",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "artist_id", "role"),
    )
    op.create_table(
        "track_external_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id", "platform", name="uq_track_external_platform"),
    )
    op.create_table(
        "track_genres",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "genre_id"),
    )
    op.create_table(
        "track_labels",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["label_id"], ["labels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "label_id"),
    )
    op.create_table(
        "track_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("section_type", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("energy", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)", name="ck_ts_confidence"
        ),
        sa.CheckConstraint("energy IS NULL OR (energy >= 0 AND energy <= 1)", name="ck_ts_energy"),
        sa.CheckConstraint("section_type >= 0 AND section_type <= 11", name="ck_ts_section_type"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transition_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_track_id", sa.Integer(), nullable=False),
        sa.Column("to_track_id", sa.Integer(), nullable=False),
        sa.Column("bpm_distance", sa.Float(), nullable=True),
        sa.Column("key_distance", sa.Integer(), nullable=True),
        sa.Column("embedding_similarity", sa.Float(), nullable=True),
        sa.Column("energy_delta", sa.Float(), nullable=True),
        sa.Column("fully_scored", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["from_track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_track_id", "to_track_id", name="uq_transition_candidates_from_to"
        ),
    )
    op.create_table(
        "transitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_track_id", sa.Integer(), nullable=False),
        sa.Column("to_track_id", sa.Integer(), nullable=False),
        sa.Column("from_section_id", sa.Integer(), nullable=True),
        sa.Column("to_section_id", sa.Integer(), nullable=True),
        sa.Column("overlap_ms", sa.Integer(), nullable=True),
        sa.Column("bpm_score", sa.Float(), nullable=True),
        sa.Column("energy_score", sa.Float(), nullable=True),
        sa.Column("harmonic_score", sa.Float(), nullable=True),
        sa.Column("spectral_score", sa.Float(), nullable=True),
        sa.Column("groove_score", sa.Float(), nullable=True),
        sa.Column("key_distance_weighted", sa.Float(), nullable=True),
        sa.Column("low_conflict_score", sa.Float(), nullable=True),
        sa.Column("overall_quality", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "bpm_score IS NULL OR (bpm_score >= 0 AND bpm_score <= 1)",
            name="ck_transitions_bpm_score",
        ),
        sa.CheckConstraint(
            "energy_score IS NULL OR (energy_score >= 0 AND energy_score <= 1)",
            name="ck_transitions_energy_score",
        ),
        sa.CheckConstraint(
            "groove_score IS NULL OR (groove_score >= 0 AND groove_score <= 1)",
            name="ck_transitions_groove_score",
        ),
        sa.CheckConstraint(
            "harmonic_score IS NULL OR (harmonic_score >= 0 AND harmonic_score <= 1)",
            name="ck_transitions_harmonic_score",
        ),
        sa.CheckConstraint(
            "key_distance_weighted IS NULL OR (key_distance_weighted >= 0 AND key_distance_weighted <= 1)",
            name="ck_transitions_key_distance_weighted",
        ),
        sa.CheckConstraint(
            "low_conflict_score IS NULL OR (low_conflict_score >= 0 AND low_conflict_score <= 1)",
            name="ck_transitions_low_conflict_score",
        ),
        sa.CheckConstraint(
            "overall_quality IS NULL OR (overall_quality >= 0 AND overall_quality <= 1)",
            name="ck_transitions_overall_quality",
        ),
        sa.CheckConstraint(
            "spectral_score IS NULL OR (spectral_score >= 0 AND spectral_score <= 1)",
            name="ck_transitions_spectral_score",
        ),
        sa.ForeignKeyConstraint(["from_track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_track_id", "to_track_id", name="uq_transitions_from_to"),
    )
    op.create_table(
        "yandex_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("yandex_track_id", sa.String(length=100), nullable=False),
        sa.Column("album_id", sa.String(length=100), nullable=True),
        sa.Column("album_title", sa.String(length=500), nullable=True),
        sa.Column("album_type", sa.String(length=50), nullable=True),
        sa.Column("album_genre", sa.String(length=200), nullable=True),
        sa.Column("album_year", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=True),
        sa.Column("release_date", sa.String(length=50), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cover_uri", sa.String(length=1000), nullable=True),
        sa.Column("explicit", sa.Boolean(), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id"),
    )
    op.create_table(
        "dj_beatgrids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_item_id", sa.Integer(), nullable=False),
        sa.Column("bpm", sa.Float(), nullable=False),
        sa.Column("first_downbeat_ms", sa.Float(), nullable=True),
        sa.Column("grid_offset_ms", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("variable_tempo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("canonical", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("bpm >= 20 AND bpm <= 300", name="ck_bg_bpm"),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)", name="ck_bg_confidence"
        ),
        sa.ForeignKeyConstraint(["library_item_id"], ["dj_library_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dj_cue_points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_item_id", sa.Integer(), nullable=False),
        sa.Column("position_ms", sa.Float(), nullable=False),
        sa.Column("kind", sa.Integer(), nullable=False),
        sa.Column("hotcue_index", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("quantized", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("source_app", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "hotcue_index IS NULL OR (hotcue_index >= 0 AND hotcue_index <= 15)",
            name="ck_cue_hotcue_index",
        ),
        sa.CheckConstraint("kind >= 0 AND kind <= 7", name="ck_cue_kind"),
        sa.ForeignKeyConstraint(["library_item_id"], ["dj_library_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dj_saved_loops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_item_id", sa.Integer(), nullable=False),
        sa.Column("in_position_ms", sa.Float(), nullable=False),
        sa.Column("out_position_ms", sa.Float(), nullable=False),
        sa.Column("length_ms", sa.Float(), nullable=True),
        sa.Column("hotcue_index", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("active_on_load", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("source_app", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "hotcue_index IS NULL OR (hotcue_index >= 0 AND hotcue_index <= 15)",
            name="ck_loop_hotcue_index",
        ),
        sa.ForeignKeyConstraint(["library_item_id"], ["dj_library_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dj_set_constraints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("constraint_type", sa.String(length=200), nullable=False),
        sa.Column("constraint_value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["set_id"], ["dj_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dj_set_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("generator_run_meta", sa.Text(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 1)",
            name="ck_set_versions_quality_score",
        ),
        sa.ForeignKeyConstraint(["set_id"], ["dj_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track_audio_features_computed",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_run_id", sa.Integer(), nullable=True),
        sa.Column("bpm", sa.Float(), nullable=True),
        sa.Column("bpm_confidence", sa.Float(), nullable=True),
        sa.Column("bpm_stability", sa.Float(), nullable=True),
        sa.Column("variable_tempo", sa.Boolean(), nullable=True),
        sa.Column("integrated_lufs", sa.Float(), nullable=True),
        sa.Column("short_term_lufs_mean", sa.Float(), nullable=True),
        sa.Column("momentary_max", sa.Float(), nullable=True),
        sa.Column("rms_dbfs", sa.Float(), nullable=True),
        sa.Column("true_peak_db", sa.Float(), nullable=True),
        sa.Column("crest_factor_db", sa.Float(), nullable=True),
        sa.Column("loudness_range_lu", sa.Float(), nullable=True),
        sa.Column("energy_mean", sa.Float(), nullable=True),
        sa.Column("energy_max", sa.Float(), nullable=True),
        sa.Column("energy_std", sa.Float(), nullable=True),
        sa.Column("energy_slope", sa.Float(), nullable=True),
        sa.Column("energy_sub", sa.Float(), nullable=True),
        sa.Column("energy_low", sa.Float(), nullable=True),
        sa.Column("energy_lowmid", sa.Float(), nullable=True),
        sa.Column("energy_mid", sa.Float(), nullable=True),
        sa.Column("energy_highmid", sa.Float(), nullable=True),
        sa.Column("energy_high", sa.Float(), nullable=True),
        sa.Column("energy_sub_ratio", sa.Float(), nullable=True),
        sa.Column("energy_low_ratio", sa.Float(), nullable=True),
        sa.Column("energy_lowmid_ratio", sa.Float(), nullable=True),
        sa.Column("energy_mid_ratio", sa.Float(), nullable=True),
        sa.Column("energy_highmid_ratio", sa.Float(), nullable=True),
        sa.Column("energy_high_ratio", sa.Float(), nullable=True),
        sa.Column("spectral_centroid_hz", sa.Float(), nullable=True),
        sa.Column("spectral_rolloff_85", sa.Float(), nullable=True),
        sa.Column("spectral_rolloff_95", sa.Float(), nullable=True),
        sa.Column("spectral_flatness", sa.Float(), nullable=True),
        sa.Column("spectral_flux_mean", sa.Float(), nullable=True),
        sa.Column("spectral_flux_std", sa.Float(), nullable=True),
        sa.Column("spectral_slope", sa.Float(), nullable=True),
        sa.Column("spectral_contrast", sa.Float(), nullable=True),
        sa.Column("key_code", sa.Integer(), nullable=True),
        sa.Column("key_confidence", sa.Float(), nullable=True),
        sa.Column("atonality", sa.Boolean(), nullable=True),
        sa.Column("hnr_db", sa.Float(), nullable=True),
        sa.Column("chroma_entropy", sa.Float(), nullable=True),
        sa.Column("hp_ratio", sa.Float(), nullable=True),
        sa.Column("onset_rate", sa.Float(), nullable=True),
        sa.Column("pulse_clarity", sa.Float(), nullable=True),
        sa.Column("kick_prominence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("bpm IS NULL OR (bpm >= 20 AND bpm <= 300)", name="ck_tafc_bpm"),
        sa.CheckConstraint(
            "bpm_confidence IS NULL OR (bpm_confidence >= 0 AND bpm_confidence <= 1)",
            name="ck_tafc_bpm_confidence",
        ),
        sa.CheckConstraint(
            "bpm_stability IS NULL OR (bpm_stability >= 0 AND bpm_stability <= 1)",
            name="ck_tafc_bpm_stability",
        ),
        sa.CheckConstraint(
            "energy_mean IS NULL OR (energy_mean >= 0 AND energy_mean <= 1)",
            name="ck_tafc_energy_mean",
        ),
        sa.CheckConstraint(
            "key_code IS NULL OR (key_code >= 0 AND key_code <= 23)", name="ck_tafc_key_code"
        ),
        sa.CheckConstraint(
            "key_confidence IS NULL OR (key_confidence >= 0 AND key_confidence <= 1)",
            name="ck_tafc_key_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["feature_extraction_runs.id"],
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id"),
        sa.UniqueConstraint("track_id"),
    )
    op.create_table(
        "track_releases",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["release_id"], ["releases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "release_id"),
    )
    op.create_table(
        "dj_beatgrid_change_points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("beatgrid_id", sa.Integer(), nullable=False),
        sa.Column("position_ms", sa.Float(), nullable=False),
        sa.Column("bpm", sa.Float(), nullable=False),
        sa.CheckConstraint("bpm >= 20 AND bpm <= 300", name="ck_bgcp_bpm"),
        sa.ForeignKeyConstraint(["beatgrid_id"], ["dj_beatgrids.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dj_set_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("set_item_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("feedback_type", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="ck_set_feedback_rating"),
        sa.ForeignKeyConstraint(["version_id"], ["dj_set_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dj_set_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("sort_index", sa.Integer(), nullable=False),
        sa.Column("transition_id", sa.Integer(), nullable=True),
        sa.Column("in_section_id", sa.Integer(), nullable=True),
        sa.Column("out_section_id", sa.Integer(), nullable=True),
        sa.Column("mix_in_point_ms", sa.Integer(), nullable=True),
        sa.Column("mix_out_point_ms", sa.Integer(), nullable=True),
        sa.Column("planned_eq", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("pinned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transition_id"], ["transitions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["version_id"], ["dj_set_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dj_set_items")
    op.drop_table("dj_set_feedback")
    op.drop_table("dj_beatgrid_change_points")
    op.drop_table("track_releases")
    op.drop_table("track_audio_features_computed")
    op.drop_table("dj_set_versions")
    op.drop_table("dj_set_constraints")
    op.drop_table("dj_saved_loops")
    op.drop_table("dj_cue_points")
    op.drop_table("dj_beatgrids")
    op.drop_table("yandex_metadata")
    op.drop_table("transitions")
    op.drop_table("transition_candidates")
    op.drop_table("track_sections")
    op.drop_table("track_labels")
    op.drop_table("track_genres")
    op.drop_table("track_external_ids")
    op.drop_table("track_artists")
    op.drop_table("timeseries_references")
    op.drop_table("spotify_metadata")
    op.drop_table("spotify_audio_features")
    op.drop_table("soundcloud_metadata")
    op.drop_table("releases")
    op.drop_table("raw_provider_responses")
    op.drop_table("provider_track_ids")
    op.drop_table("key_edges")
    op.drop_table("feature_extraction_runs")
    op.drop_table("embeddings")
    op.drop_table("dj_sets")
    op.drop_table("dj_playlist_items")
    op.drop_table("dj_library_items")
    op.drop_table("beatport_metadata")
    op.drop_table("app_exports")
    op.drop_table("tracks")
    op.drop_table("spotify_playlist_metadata")
    op.drop_table("spotify_artist_metadata")
    op.drop_table("spotify_album_metadata")
    op.drop_table("providers")
    op.drop_table("labels")
    op.drop_table("keys")
    op.drop_table("genres")
    op.drop_table("dj_playlists")
    op.drop_table("artists")
    # ### end Alembic commands ###
