"""add mfcc_vector energy_mid_ratio and indexes

Revision ID: b2daa4e04efd
Revises: a1b2c3d4e5f6
Create Date: 2026-03-27 01:33:42.574046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2daa4e04efd'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_track_audio_features_computed_bpm'), 'track_audio_features_computed', ['bpm'], unique=False)
    op.create_index(op.f('ix_track_audio_features_computed_integrated_lufs'), 'track_audio_features_computed', ['integrated_lufs'], unique=False)
    op.create_index(op.f('ix_track_audio_features_computed_key_code'), 'track_audio_features_computed', ['key_code'], unique=False)
    op.create_index(op.f('ix_track_audio_features_computed_mood'), 'track_audio_features_computed', ['mood'], unique=False)
    op.create_index(op.f('ix_track_sections_track_id'), 'track_sections', ['track_id'], unique=False)
    op.create_index(op.f('ix_tracks_status'), 'tracks', ['status'], unique=False)
    op.create_index(op.f('ix_transition_candidates_from_track_id'), 'transition_candidates', ['from_track_id'], unique=False)
    op.create_index(op.f('ix_transition_candidates_to_track_id'), 'transition_candidates', ['to_track_id'], unique=False)
    op.create_index(op.f('ix_transitions_from_track_id'), 'transitions', ['from_track_id'], unique=False)
    op.create_index(op.f('ix_transitions_to_track_id'), 'transitions', ['to_track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transitions_to_track_id'), table_name='transitions')
    op.drop_index(op.f('ix_transitions_from_track_id'), table_name='transitions')
    op.drop_index(op.f('ix_transition_candidates_to_track_id'), table_name='transition_candidates')
    op.drop_index(op.f('ix_transition_candidates_from_track_id'), table_name='transition_candidates')
    op.drop_index(op.f('ix_tracks_status'), table_name='tracks')
    op.drop_index(op.f('ix_track_sections_track_id'), table_name='track_sections')
    op.drop_index(op.f('ix_track_audio_features_computed_mood'), table_name='track_audio_features_computed')
    op.drop_index(op.f('ix_track_audio_features_computed_key_code'), table_name='track_audio_features_computed')
    op.drop_index(op.f('ix_track_audio_features_computed_integrated_lufs'), table_name='track_audio_features_computed')
    op.drop_index(op.f('ix_track_audio_features_computed_bpm'), table_name='track_audio_features_computed')
    # ### end Alembic commands ###
