"""add mfcc_vector column

Revision ID: e28735693789
Revises: 51468ce1356a
Create Date: 2026-03-26 04:02:45.703168

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e28735693789"
down_revision: str | None = "51468ce1356a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track_audio_features_computed",
        sa.Column("mfcc_vector", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track_audio_features_computed", "mfcc_vector")
    # ### end Alembic commands ###
