"""add analysis_level to track_audio_features_computed

Revision ID: 90b8916fe80b
Revises: b2daa4e04efd
Create Date: 2026-03-27 05:27:47.914747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90b8916fe80b"
down_revision: str | None = "b2daa4e04efd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track_audio_features_computed",
        sa.Column("analysis_level", sa.Integer(), server_default="0", nullable=False),
    )
    # Backfill: existing rows with bpm data were fully analyzed (L3)
    op.execute("UPDATE track_audio_features_computed SET analysis_level = 3 WHERE bpm IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track_audio_features_computed", "analysis_level")
    # ### end Alembic commands ###
